version: 0.2
phases:
  pre_build:
    commands:
      - java -version
      - gradle -v
      - mkdir -p /home/application/
      - rm -rf /home/application/*
      - cp -rf * /home/application/
      - chmod 777 -R /home/application/*
      - cd /home/application/
      - gradle build --no-daemon
      - ./build-native-image.sh
      - chmod 755 bootstrap
      - chmod 755 server
      - zip -j function.zip bootstrap libsunec.so cacerts server
      - cd
      - pwd
      - ls -lrt
  build:
    commands:
      - echo "test start"
  post_build:
    commands:
      - echo "Nothing to do"
artifacts:
  files:
      - './result.txt'
