AWSTemplateFormatVersion : '2010-09-09'
Description: Import Lambda
Resources:
  LambdaResource:
    Type: AWS::Lambda::Function
    DeletionPolicy: Retain
    Properties:
      FunctionName: pac-pe-api-post-01
      Role: arn:aws:iam::536824749084:role/pis-Lambda-DynamoDB-Role
      Runtime: provided.al2
      Handler: function.handler
      Code: ./
