AWSTemplateFormatVersion: '2010-09-09'
Description: Sample src Template for SpringNative

Resources:
  PACAPPD:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: pac-pe-api-post-01
      Handler: function.handler
      Role: arn:aws:iam::114872357316:role/PAC-PE-API-POST-role-nolpgpun
      Runtime: provided.al2
      Code:
        S3Bucket: common-use-for-andre-and-all
        S3Key: pac-snb
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
Outputs:
  PACAPPD:
    Description: "PAC Lambda Function ARN"
    Value: !GetAtt PACAPPD.Arn
